name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
   { pattern = "docker.duizhang.fun", custom_domain = true },
   { pattern = "quay.duizhang.fun", custom_domain = true },
   { pattern = "gcr.duizhang.fun", custom_domain = true },
   { pattern = "k8s-gcr.duizhang.fun", custom_domain = true },
   { pattern = "k8s.duizhang.fun", custom_domain = true },
   { pattern = "ghcr.duizhang.fun", custom_domain = true },
   { pattern = "cloudsmith.duizhang.fun", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.duizhang.fun", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
